### ISSUE TITLE
Trying to remove a inexistant policy by policy_name crashes fortimgr_policy

### ISSUE THREAD

**Issue by jcsicard** [networktocode/fortimanager-ansible#58]
```
    - name:  ensure inexistant policy is absent
      fortimgr_policy:
        host: "{{ fortimanager }}"
        session_id: "{{ session.session_id }}"
        adom: "{{ adom_name }}"
        state: absent
        package: "{{ policy_package_name }}"
        policy_name: "inexistant-policy-name"
```

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_GLEqr9/ansible_module_fortimgr_policy.py\", line 2395, in <module>\n    main()\n  File \"/tmp/ansible_GLEqr9/ansible_module_fortimgr_policy.py\", line 2369, in main\n    policy_id = results[\"config\"][\"id\"]\nKeyError: 'id'\n",
    "module_stdout": "",
    "rc": 0
}

MSG:

MODULE FAILURE
```
