### ISSUE TITLE
unlock users

### ISSUE THREAD

**Issue by sinu** [networktocode/fortimanager-ansible#74]
@jathanism @dgarros @gkroone @jedelman8 @jerej  is there any way to unlock the user who logged in via gui.  we have bunch of operation engineers if anyone one making adom on locked mode then ansible is failing to execute. how we can handle this programmatically

**Comment by sinu** [comment]
@jmcgill298 can you help me here

**Comment by jmcgill298** [comment]
@sinu I don't think that is possible, and is not good practice to kick someone out in the middle of their changes. Some alternative solutions:

1) Use `retry` and `until` on the lock task to keep trying to lock the ADOM until it is successful
2) Find out why the engineers need to lock the ADOM, and create playbooks that handle those use cases
3) Have predefined scheduled jobs for Automation Tasks to run, and require that users keep ADOMs unlocked during those times.

Here is an example of the first option:
```yaml
- fortimgr_lock:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    adom: "lab"
    lock: True
  register: "fmg_lock"
  until: "fmg_lock.locked"
  retries: 10
  delay: 20
```
